server:
  port: 8080

spring:
  application:
    name: demo

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://${DB_URL}/${DB_TABLE}
    username: ${DB_ID}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

social:
  google:
    authorization-uri: https://accounts.google.com/o/oauth2/auth
    token-uri: https://oauth2.googleapis.com/token
    user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
    user-name-attribute: id
  kakao:
    authorization-uri: https://kauth.kakao.com/oauth/authorize
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
    user-name-attribute: id
  naver:
    authorization-uri: https://nid.naver.com/oauth2.0/authorize
    token-uri: https://nid.naver.com/oauth2.0/token
    user-info-uri: https://openapi.naver.com/v1/nid/me
    user-name-attribute: response

jwt:
  access-token-time: 9999999  #3600 # 60 * 60 1시간
  refresh-token-time: 9999999  #604800 # 60 * 60 * 24 * 7 1주일

payment:
  price: 6900
  second-week-sunday: 0 0 0 ? * 1#2 # 매월 2번 째 주 일요일 0시
  four-week-sunday: 0 0 0 ? * 1#2 # 매월 4번 째 주 일요일 0시

family:
  code-len: 6 # 0<=familyId<=2조 :: 이상의 family 생성시 자리 수 증가 필요

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
  info:
    title: "TheFirstCommit 프로젝트 API 명세서"
    description: "가족 기반 소셜 서비스 프로젝트의 API 문서입니다."
    version: "v1.0.0"
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
